adjective1 = input("Adjective: ")
noun1 = input("Noun: ")
adjective2 = input("Adjective: ")
verb1 = input("Verb: ")
adjective3 = input("Adjective: ")

print(f"Today I went to a {adjective1} restaurant.")
print(f"They server me a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")